name: autofix.ci
on:
  pull_request:
    paths:
      - "poetry.lock"
      - "pyproject.toml"
      - "src/backend/**"
      - "tests/**"
env:
  POETRY_VERSION: "1.8.2"

jobs:
  lint:
    name: Run Ruff Check and Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: install-pinned/ruff@9dc868a5f5702250582fc7516d8caf489da24d33
      - run: ruff check --fix-only .
      - run: ruff format .
      - uses: autofix-ci/action@dd55f44df8f7cdb7a6bf74c78677eb8acd40cd0a
  lock:
    name: Check Poetry lock
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: "./.github/actions/poetry_caching"
        with:
          python-version: "3.12"
          poetry-version: ${{ env.POETRY_VERSION }}
          cache-key: ${{ runner.os }}-poetry-${{ env.POETRY_VERSION }}-${{ hashFiles('**/poetry.lock') }}
      - name: Check poetry.lock
        id: check
        run: |
          poetry check --lock
        continue-on-error: true

      - name: Run lock
        if : steps.check.outcome == 'failure'
        run: |
          make lock
      - uses: autofix-ci/action@dd55f44df8f7cdb7a6bf74c78677eb8acd40cd0a
